paths:
  logdir_base: "{{project_root}}/tensorboard"
  cache: "{{project_root}}/data/cache"
  results: "{{project_root}}/results"
  
general: 
  task: "bert-pretrain"
  seed: 125
  note: "a quick note about this training run. this note will show up in tensorboard."

params:
  save_criterion: "min"
  save_checkpoint: True

  # bert params
  next_sent_prob: .5
  mlm_prob: .15
  mask_replace_keep_dist: [.8, .1, .1]

  # model params
  d_model: 1024
  n_head: 16
  n_layers: 24
  dim_feedforward: 4096
  dropout: 0.1
  dtype: "bfloat16"
  seq_len: 128

  # optimizer params
  lr: .0001
  weight_decay: 0.01
  clip_max_norm: 1

  # optimizer scheduler
  sched_step_size: 1
  sched_gamma: 0.9

  # data params
  num_proc: 8
  shuffle: True
  batch_size: 4
  num_epochs: 2
  eval_freq: 400
  log_freq: 50
  num_test_samples: 25

  # misc options
  skip_first_eval: true

# Used for hyperparameter search.
# For each parameter, if "num_samples" isn't specified, 
# only the values specificed in the "values" argument will be used
search_params:
  search_type: 'random'
  search_steps: 10
  train_step_limit: 2400
  lr: 
    values: [1.0e-5, 1.0e-3]
    dtype: "float"
  weight_decay:
    values: [1.0e-7, 1.0e-1]
    dtype: "float"