paths:
  logdir_base: "{{project_root}}/tensorboard"
  cache: "{{project_root}}/data/cache"
  results: "{{project_root}}/results"
  
general: 
  task: "mnist_mlp"
  seed: 125
  note: "a quick note about this training run. this note will show up in tensorboard."

params:
  save_criterion: "max"
  save_checkpoint: True

  # model params
  in_size: 784
  hidden_dim: 500
  dropout: 0.05
  num_classes: 10

  # optimizer params
  lr: .001
  weight_decay: 0
  beta1: .9
  beta2: .999
  eps: 1.0e-8
  clip_max_norm: 1

  # optimizer scheduler
  sched_step_size: 5
  sched_gamma: 0.999

  # data params
  num_proc: 20
  shuffle: True
  batch_size: 1024
  num_epochs: 30
  eval_freq: 50
  log_freq: 10

  # misc options
  skip_first_eval: True

# Used for hyperparameter search.
# For each parameter, if "num_samples" isn't specified, 
# only the values specificed in the "values" argument will be used
search_params:
  search_type: 'grid'
  step_limit: null
  lr: 
    values: [1.0e-5, 1.0e-3]
    dtype: "float"
  weight_decay:
    values: [1.0e-7, 1.0e-5]
    dtype: "float"
  sched_gamma: 
    values: [.98, .9]
    num_samples: 10
    dtype: "float"
  sched_step_size: 
    values: [20, 50, 100]
    dtype: "int"
