paths:
  logdir_base: "{{project_root}}/tensorboard"
  cache: "/data/john/cache"
  results: "{{project_root}}/results"
  
general: 
  task: "sent_emb_reorder"
  seed: 128
  note: "a quick note about this training run. this note will show up in tensorboard."

params:
  save_criterion: "max"
  save_checkpoint: True

  # model params
  encoder: "mixedbread-ai/mxbai-embed-large-v1"
  freeze_encoder: False
  d_model: 1024
  nhead: 16
  #dim_feedforward: 2048
  dim_feedforward: 4096
  dropout: 0.0853056472
  activation: 'gelu'
  n_layers: 2
  sent_len: 128
  seq_len: 128
  with_positions: True

  dtype: "float32"

  # optimizer params
  lr: 0.0000633969
  encoder_lr: 5.0e-5
  weight_decay: 0.0601446424
  encoder_weight_decay: .0601
  beta1: .9
  beta2: .999
  eps: 1.0e-8
  clip_max_norm: 1

  # optimizer scheduler
  sched_step_size: 5
  sched_gamma: 0.998

  # data params
  num_proc: 10
  shuffle: True
  batch_size: 16
  num_epochs: 40
  eval_freq: 50
  log_freq: 25
  num_test_samples: 25

  # misc options
  skip_first_eval: True

# Used for hyperparameter search.
# For each parameter, if "num_samples" isn't specified, 
# only the values specificed in the "values" argument will be used
search_params:
  search_type: 'random'
  search_steps: 60
  train_step_limit: 300
  weight_decay:
    values: [1.0e-6, 1.0e-1]
    num_samples: 10
    dtype: "float"
  encoder_weight_decay:
    values: [1.0e-6, 1.0e-1]
    num_samples: 10
    dtype: "float"
  lr: 
    values: [1.0e-7, 1.0e-4]
    num_samples: 10
    dtype: "float"
  encoder_lr: 
    values: [1.0e-7, 1.0e-4]
    num_samples: 10
    dtype: "float"
  dropout:
    values: [0.0, 0.2]
    num_samples: 10
    dtype: "float"

