paths:
  logdir_base: "{{project_root}}/tensorboard"
  cache: "{{project_root}}/data/cache"
  results: "{{project_root}}/results"
  
general: 
  task: "sent_emb_reorder_5"
  seed: 127
  note: "a quick note about this training run. this note will show up in tensorboard."

params:
  save_criterion: "max"
  save_checkpoint: True

  # model params
  d_model: 1024
  nhead: 16
  dim_feedforward: 2048
  dropout: 0.00
  activation: 'gelu'
  n_layers: 1
  seq_len: 5
  with_positions: True

  dtype: "float32"

  # optimizer params
  lr: 6.06221e-5
  weight_decay: .0061027885
  beta1: .9
  beta2: .999
  eps: 1.0e-8
  clip_max_norm: 1

  # optimizer scheduler
  sched_step_size: 5
  sched_gamma: 0.9

  # data params
  num_proc: 20
  shuffle: True
  batch_size: 32
  num_epochs: 10
  eval_freq: 300
  log_freq: 100
  num_test_samples: 25

  # misc options
  skip_first_eval: True

# Used for hyperparameter search.
# For each parameter, if "num_samples" isn't specified, 
# only the values specificed in the "values" argument will be used
search_params:
  search_type: 'random'
  search_steps: 60
  train_step_limit: null
  weight_decay:
    values: [1.0e-5, 1.0e-2]
    num_samples: 10
    dtype: "float"
  lr: 
    values: [1.0e-6, 1.0e-3]
    num_samples: 10
    dtype: "float"
