paths:
  logdir_base: "{{project_root}}/tensorboard"
  cache: "{{project_root}}/data/cache"
  results: "{{project_root}}/results"
  
general: 
  task: "sofsat/lora"
  seed: 125
  note: "a quick note about this training run. this note will show up in tensorboard."

params:
  save_criterion: "min"
  save_checkpoint: False 

  # model params
  #base_model: "mistralai/Mistral-7B-v0.1"
  #base_model: "openai-community/gpt2"
  base_model: "openai-community/gpt2-xl"
  lora_r: 8
  lora_alpha: 8
  lora_dropout: 0.1
  seq_len: 512
  dtype: "bfloat16"

  # optimizer params
  lr: .0001
  weight_decay: 0.01
  clip_max_norm: 1

  # optimizer scheduler
  sched_step_size: 1
  sched_gamma: 0.9

  # data params
  num_proc: 4
  shuffle: True
  batch_size: 8
  num_epochs: 10
  eval_freq: 300
  log_freq: 50

  # misc options
  skip_first_eval: True

# Used for hyperparameter search.
# For each parameter, if "num_samples" isn't specified, 
# only the values specificed in the "values" argument will be used
search_params:
  search_type: 'random'
  search_steps: 60
  train_step_limit: 900
  lr: 
    values: [5.0e-4, 1.0e-3]
    num_samples: 10
    dtype: "float"
  weight_decay:
    values: [1.0e-7, 1.0e-5]
    num_samples: 10
    dtype: "float"
