paths:
  logdir_base: "{{project_root}}/tensorboard"
  cache: "{{project_root}}/data/cache"
  results: "{{project_root}}/results"
  
general: 
  task: "vit_cls"
  seed: 126
  note: "a quick note about this training run. this note will show up in tensorboard."

params:
  save_criterion: "max"
  save_checkpoint: True

  # model params
  d_model: 768
  n_head: 12
  n_layers: 6
  dim_feedforward: 768
  dropout: 0.1
  image_shape: [32, 32, 3]
  patch_width: 4
  patch_height: 4
  normalize_factor: 256
  dtype: "bfloat16"

  # optimizer params
  lr: 3.596055e-4
  weight_decay: 2.5741e-6
  clip_max_norm: 1

  # optimizer scheduler
  sched_step_size: 20
  sched_gamma: 0.95813

  # data params
  num_proc: 24
  shuffle: True
  batch_size: 512
  num_epochs: 30
  eval_freq: 250
  log_freq: 250

  # misc options
  skip_first_eval: True

# Used for hyperparameter search.
# For each parameter, if "num_samples" isn't specified, 
# only the values specificed in the "values" argument will be used
search_params:
  search_type: 'random'
  search_steps: 60
  train_step_limit: 2000
  weight_decay:
    values: [1.0e-7, 1.0e-4]
    num_samples: 10
    dtype: "float"
  lr: 
    values: [1.0e-5, 2.0e-3]
    num_samples: 10
    dtype: "float"
  batch_size:
    values: [512, 1024]
    dtype: "int"
  sched_step_size: 
    values: [10, 15]
    dtype: "int"
  sched_gamma:
    values: [.98, .9]
    num_samples: 10
    dtype: "float"
  dropout:
    values: [0.05, 0.1]
    dtype: "float"
  patch_width:
    values: [4, 8, 16]
    dtype: "int"
  patch_height:
    values: [4, 8, 16]
    dtype: "int"
